### ISSUE TITLE
Compilation error.

### ISSUE THREAD

**Issue by Midnoclose** [LuigiBlood/zeldadisk#1]
When I attempt to compile the disk, I get this error:
```
error: file not found: zeldadisk/ezlj_nes_message_table.bin
zeldadisk/EZLJ_DISK_FileSystem.asm:16:1: insert "ezlj_nes_message_table.bin"
bass: assembly failed
```
How can I extract the missing files?

**Comment by LuigiBlood** [comment]
There are missing files you cannot have anyway. This one is like the only few ones that comes from Zelda OoT.

It's impossible to build this properly without changing the code.

EDIT: I know that the readme says otherwise but I expected to update this quicker. Unfortunately that has to wait.
